---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Coronavirus-apps: voorkomen is beter dan genezen**

Individuele privacy is een groot goed. Hoe weeg je dat af tegen het
brede maatschappelijke belang van de inzet van COVID-19 zoek-en-volg
apps? Wij, 3 bezorgde burgers, doen een
[voorstel](https://pietstam.nl/coronavirus-privacy/) voor 10 beoordelingscriteria om die afweging zorgvuldig te kunnen maken. Ons uitgangsunt
daarbij is dat privacy geen absoluut recht is, maar wel een noodzaak.

**Auteurs**

Wij, 3 bezorgde burgers, hebben dit voorstel op persoonlijke titel geschreven. Onze namen zijn:

* Piet Stam, gezondheidseconoom
* Peter Nobels, zorg-IT management consultant
* Marco Woesthuis, arts (niet praktizerend)

**Commmunity**

We hopen op inbreng van andere bezorgde burgers, zodat de lijst wordt
aangescherpt en we samen de overheid aan een maatschappelijk gedragen toetsingskader
helpen. Daarom hebben we de lijst met 10 uitgangspunten in een [Wiki](https://github.com/pjastam/coronavirus-privacy/wiki)
gezet, zodat iedereen kan meehelpen aan de aanscherping. Het enige dat je daarvoor nodig hebt is een GitHub login.

**Publicatierechten**

Onze en uw inbreng staat in een openbare
[repository](https://github.com/pjastam/coronavirus-privacy) op
[GitHub](https://nl.wikipedia.org/wiki/GitHub) en valt onder de
[Creative Commons Attribution 4.0
International](https://creativecommons.org/licenses/by/4.0/) licentie.

**Originele versie**

De originele versie van ons voorstel is te vinden op
[GitHub](https://github.com/pjastam/coronavirus-privacy).

**Contact**

Vragen of feedback kun je het beste
[hier](https://github.com/pjastam/coronavirus-privacy/issues) invoeren.
Dat levert een directe bijdrage aan de openbare discussie die wij
nastreven. Als u me rechtstreeks wilt benaderen dan is een DM via
[Twitter](https://twitter.com/pjastam%22) het handigst.
